# Generated by Django 3.1.4 on 2021-01-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0002_userresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
