# Generated by Django 3.1.4 on 2021-01-04 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0004_auto_20210104_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresults',
            name='score',
        ),
        migrations.AddField(
            model_name='userresults',
            name='Exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Quizapp.exam'),
            preserve_default=False,
        ),
    ]
