# Generated by Django 3.1.5 on 2021-01-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0006_auto_20210108_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='filltheblanks',
            name='user_answer',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filltheblanks',
            name='question',
            field=models.TextField(max_length=100),
        ),
    ]
