# Generated by Django 3.1.5 on 2021-01-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0007_auto_20210108_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filltheblanks',
            name='user_answer',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
