# Generated by Django 3.1.5 on 2021-01-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0009_userprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprogress',
            options={'verbose_name_plural': 'UserProgress'},
        ),
        migrations.AddField(
            model_name='userprogress',
            name='current_page',
            field=models.IntegerField(default=1),
        ),
    ]
