# Generated by Django 3.1.5 on 2021-01-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0011_auto_20210109_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='current_page',
            field=models.IntegerField(default=1),
        ),
    ]
