# Generated by Django 3.1.5 on 2021-01-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0013_auto_20210111_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filltheblanks',
            name='user_answer',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='score_answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='user_answer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='UserResults',
        ),
    ]
