# Generated by Django 3.1.4 on 2021-01-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0003_exam_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='score',
        ),
        migrations.RemoveField(
            model_name='userresults',
            name='totalquestions',
        ),
        migrations.AddField(
            model_name='userresults',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
