# Generated by Django 3.1.5 on 2021-01-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0005_auto_20210104_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillTheBlanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('blank_answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='Correct_ans',
            new_name='correct_ans',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='Option1',
            new_name='option1',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='Option2',
            new_name='option2',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='Option3',
            new_name='option3',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='Option4',
            new_name='option4',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='Question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='userresults',
            old_name='Exam',
            new_name='exam',
        ),
    ]
