# Generated by Django 3.1.5 on 2021-01-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0010_auto_20210109_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='current_page',
            field=models.IntegerField(),
        ),
    ]
