# Generated by Django 3.1.5 on 2021-01-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0012_auto_20210109_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filltheblanks',
            name='user_answer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
