# Generated by Django 3.1.5 on 2021-01-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0015_auto_20210112_1356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='FillTheBlanks',
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
